### ISSUE TITLE
Implement V/Line tracker

### ISSUE THREAD

**Issue by eyeballcode** [TransportVic/TransportVic2#3]
Todo:

- [x] Ensure getVNETDepartures can work with both up and down

- [x] Add additional logic for recording in new collection (`vline trips`) the consist of trips recorded

- [x] Add a tracker page

**Comment by eyeballcode** [comment]
a46f531 just about wraps it up - tracker data is now shown when retrieving timings
